{% set name = "neo" %}
{% set version = "0.4.1" %}

package:
  name: python-{{ name }}
  version: {{ version }}

source:
  fn: python-{{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: f706df3a1bce835cb490b812ac198a6e

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.3.0
    - quantities >=0.9.0

  run:
    - python
    - numpy >=1.3.0
    - quantities >=0.9.0

test:
  imports:
    - neo
    - neo.core
    - neo.io
    - neo.test
    - neo.test.iotest

about:
  home: http://neuralensemble.org/neo
  license: BSD 3-Clause
  summary: A Python package for representing and reading electrophysiology data.

extra:
  recipe-maintainers:
    - apdavison
    - jakirkham
    - samuelgarcia
