travis:
  secure:
    BINSTAR_TOKEN: Hcm9sADZ6aicf5NaFEK1PXuE07liJiaC9aLRIhTMSKSCBGvrgnmvIe3FnlC7JW+T1vLu30vuc2zhhWEh5YEjtsNIO4TfFcU9g1bpLLOVDrzrLpk6Jgs1EwZOvGlOsysf/GREhzszsg7iFj6rQNn5cuVDaJ/GN28kLPrCiX54KSLbWM4o+iWg99qKbWL2+3kDW7rUEEi3U6P3m2QuyJp2BURzZblhZ6ESKrvFGOywsqalhnAwCLP4ZabEBuQnJsXv7WEHnJnXFFJDAxby7bTSnpsZ0K8xo+CD6NRAv02EB7btVoXOJTusqasYlWvMMNRs9pN0wMcq8StnJOYeu1GfbOdlYnvbvbfUNbRNNBIpO9yOOTmU6UFehqAY/CEdujKGeqoUZAwmVBTXIFmn0DFrfGGkEIdIigLbpVVPDWn8hyefkhTs42cjX5P2aLLQZW74lkxcnXWBpRGghzR5oxTVkTk0hdhGA+rdzbVmqzoDHfh+ikHRG0nlIVV8jK1edPVZWWnWGJ7o2smff3FlpgYvXHuVBcppvrZ7N29v3Qblhb8sNG7e2wn6zMlm3yOvjmC+GPaXoc7Suk9NNnB/DhMrmKjqa6BTsa0JsJMGRTwz/L8sea37ZhM596Wh+VfGs2B1aqWWTtygkHOIfqiWLYpLqm8B91WJpNCriQOUpGAOghY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
