travis:
  secure:
    BINSTAR_TOKEN: Th7WUv050J1kyp2j177HVuOQHfjMq620Lt63nTgsjwHTf2pHGkZIUxV7U3O1xj5TJlMaF/+sx6e7r879AoOnBQlnpRI08rhp0qLAcot9y+XJMWDctB2fCijyN1ty818iip5ChqfhBxCtKzJnvcfs9T1YOut3vRCi7mLqwg/R0915iNu1MoZNPPr/9Qulc9q+FZZu2mxwW3B5lNfLnmRKV30IQCqUQvYyK+vgX5YZNFl0eZIxUURe3SwjpLdaryGdIagE/H54johHTZBNFVVJwB/SELEtC+OsG0Sjf3bsj+iRBWxAeW7Ek3EHqTmbgT88sQmW6aS2drxQihBk1f7E0So4HAwIKSEPhyCohj1VFtf/f09mBOHFpyFhubLpRiv807MWhqgZK5nMsHrCf8pNf8b49ggOomE1mXWEA4AHSwzBWUB7wLLXdsGoxrDUViDIEEm3/RPFejocm7LWQVGu+fKG6cRkdDCzBcd4yg7qimwK+KhmcquN/0kY2MJZHANg5oT2StUZxMAeSAiN1OK/ar5nnRY6cJCIBxa6Pag3hdmN4+uY/bHw1CH0WODQlE7z0FdxZXGQgu/zMREiHZ/Ta81Q2Wla36SN8EmqttPaXLNJNlwLBHEtAuZ/m2UeyXaE7TGWufKNfi98plYEzJ0S4jL8+PMYw2puqfSkCL2xnqA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
